# Generated by Django 4.2.4 on 2023-08-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('contents', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('category', models.SmallIntegerField(choices=[(1, '일반'), (2, '배송'), (3, '상품'), (4, '이벤트')], default=1)),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
    ]
