# Generated by Django 4.2.4 on 2023-08-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.SmallIntegerField(choices=[(1, 'COFFEE'), (2, 'CAPSULE'), (3, 'CUPS'), (4, 'ACC')], default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
