# Generated by Django 4.2.4 on 2023-08-11 07:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffee', '0002_product_category_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='jjim',
            field=models.ManyToManyField(related_name='jjim', to=settings.AUTH_USER_MODEL),
        ),
    ]
